import axios from 'axios';

/**
 * Enhanced Image Generation Command for KiwBot using SDXL API
 */
export const handleImagine = async (command, sock, msg, args, from, sender) => {
    if (command !== '/imagine') return;

    if (args.length === 0) {
        return await sock.sendMessage(from, { 
            text: '🎨 *KiwBot AI Image Generator*\n\nUsage:\n/imagine [prompt] [flags]\n\nFlags:\n--story / --portrait (Portrait 9:16)\n--landscape (Landscape 16:9)\n\nExample:\n/imagine a cyberpunk city --landscape' 
        });
    }

    const rawInput = args.join(' ');
    let prompt = rawInput;
    
    let width = 1024;
    let height = 1024;
    let ratioLabel = '1:1 (Square)';

    if (rawInput.includes('--story') || rawInput.includes('--portrait') || rawInput.includes('--ar 9:16')) {
        width = 768;
        height = 1344;
        ratioLabel = '9:16 (Portrait)';
        prompt = prompt.replace('--story', '').replace('--portrait', '').replace('--ar 9:16', '');
    } else if (rawInput.includes('--landscape') || rawInput.includes('--ar 16:9')) {
        width = 1344;
        height = 768;
        ratioLabel = '16:9 (Landscape)';
        prompt = prompt.replace('--landscape', '').replace('--ar 16:9', '');
    }

    prompt = prompt.replace(/[*\"_#]/g, '').trim();

    // Notify user
    const loadingMsg = await sock.sendMessage(from, { text: '🎨 *KiwBot is generating your image...* please wait.' }, { quoted: msg });

    const apiKey = 'c9308e3c266c4d859867aa691ce92be7';
    const apiUrl = 'https://gateway.appypie.com/getImage/v1/getSDXLImage';

    const payload = {
        prompt: prompt,
        negative_prompt: "Low-quality, blurry image, with any other animals. Avoid abstract or cartoonish styles, dark or gloomy atmosphere, unnecessary objects or distractions in the background, harsh lighting, and unnatural colors.",
        width: width,
        height: height,
        num_steps: 20,
        guidance_scale: 5,
        seed: Math.floor(Math.random() * 1000000)
    };

    try {
        const response = await axios.post(apiUrl, payload, {
            headers: {
                'Content-Type': 'application/json',
                'Ocp-Apim-Subscription-Key': apiKey,
                'Cache-Control': 'no-cache'
            },
            timeout: 60000 // 60s timeout
        });

        // The API typically returns JSON with an imageUrl or the image data directly.
        // Based on docs, it returns { imageUrl: "..." }
        
        let imageUrl = null;
        if (response.data && response.data.imageUrl) {
            imageUrl = response.data.imageUrl;
        } else if (typeof response.data === 'string' && response.data.includes('http')) {
             // Fallback if it returns just a string
             try {
                const parsed = JSON.parse(response.data);
                imageUrl = parsed.imageUrl;
             } catch (e) {
                // Check if the string itself is a url
                if (response.data.startsWith('http')) imageUrl = response.data;
             }
        }

        if (!imageUrl) {
            throw new Error('No image URL in response: ' + JSON.stringify(response.data));
        }

        // Send the image
        // We can send directly via URL, but downloading ensures we have the buffer 
        // and avoids some WhatsApp URL preview issues.
        const imageResponse = await axios.get(imageUrl, { responseType: 'arraybuffer' });
        const buffer = Buffer.from(imageResponse.data, 'binary');

        const caption = `🎨 *Generated by KiwBot*\n\n📝 *Prompt:* ${prompt}\n📐 *Shape:* ${ratioLabel}`;
        
        // Delete loading message
        await sock.sendMessage(from, { delete: loadingMsg.key });

        await sock.sendMessage(from, { 
            image: buffer, 
            caption: caption 
        }, { quoted: msg });

    } catch (error) {
        console.error('Imagine Command Error:', error.response ? error.response.data : error.message);
        
        let errorMessage = '❌ Failed to generate image.';
        if (error.response && error.response.status === 401) {
            errorMessage = '❌ API Key Invalid or Expired.';
        } else if (error.message.includes('timeout')) {
            errorMessage = '❌ Generation timed out.';
        } else {
            errorMessage = `❌ Error: ${error.message.slice(0, 50)}...`;
        }

        await sock.sendMessage(from, { text: errorMessage, edit: loadingMsg.key });
    }
};
