import { exec } from 'child_process';
import path from 'path';
import fs from 'fs';
import aiService from '../services/ai.js';

/**
 * Enhanced Image Generation Command using Perchance
 * Features:
 * - Prompt Enhancement via internal AI
 * - Aspect Ratio Control (--ar, --story, --landscape)
 * - Uses Perchance (Local Python Integration)
 */
export const handleImagine = async (command, sock, msg, args, from, sender) => {
    if (command !== '/imagine') return;

    // 1. Basic Input Validation
    if (args.length === 0) {
        return await sock.sendMessage(from, { 
            text: '🎨 *Perchance Image Generator*\n\nUsage:\n/imagine [prompt] [flags]\n\nFlags:\n--story / --portrait (Portrait)\n--landscape (Landscape)\n\nExample:\n/imagine a cyberpunk city --landscape' 
        });
    }

    const rawInput = args.join(' ');
    let prompt = rawInput;
    let shape = 'square';
    let ratioLabel = '1:1';

    // 2. Parse Aspect Ratio Flags
    if (rawInput.includes('--story') || rawInput.includes('--portrait') || rawInput.includes('--ar 9:16')) {
        shape = 'portrait';
        ratioLabel = 'Portrait';
        prompt = prompt.replace('--story', '').replace('--portrait', '').replace('--ar 9:16', '');
    } else if (rawInput.includes('--landscape') || rawInput.includes('--ar 16:9')) {
        shape = 'landscape';
        ratioLabel = 'Landscape';
        prompt = prompt.replace('--landscape', '').replace('--ar 16:9', '');
    }

    // Clean up prompt
    prompt = prompt.replace(/[*\"_#]/g, '').trim();

    // Notify user that we are working on it
    const loadingMsg = await sock.sendMessage(from, { text: '🎨 *Generating image (Perchance)...* please wait.\n_This may take a minute as it uses Playwright._' }, { quoted: msg });

    const tempDir = path.join(process.cwd(), 'temp');
    if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir);
    
    const outPath = path.join(tempDir, `gen_${Date.now()}.png`);
    
    // Detect OS for Python path
    const isWindows = process.platform === 'win32';
    const pythonPath = isWindows 
        ? path.join(process.cwd(), 'perchance', 'venv', 'Scripts', 'python.exe')
        : path.join(process.cwd(), 'perchance', 'venv', 'bin', 'python3');
        
    const scriptPath = path.join(process.cwd(), 'perchance', 'gen_image.py');

    // Use a promise to handle the exec call
    const runPython = () => new Promise((resolve, reject) => {
        // Check if venv exists
        if (!fs.existsSync(pythonPath)) {
            return reject(new Error(`Python Virtual Environment not found at ${pythonPath}. Please run setup commands on VPS.`));
        }

        // Escape prompt for shell
        const escapedPrompt = prompt.replace(/"/g, '\\"');
        
        // Use environment variables to ensure PYTHONPATH is correct
        const env = { 
            ...process.env, 
            PYTHONPATH: path.join(process.cwd(), 'perchance') 
        };

        const cmd = `"${pythonPath}" "${scriptPath}" --prompt "${escapedPrompt}" --out "${outPath}" --shape ${shape}`;
        
        exec(cmd, { env }, (error, stdout, stderr) => {
            if (error) {
                console.error('Python Error:', stderr);
                return reject(new Error(stderr || stdout || error.message));
            }
            if (stdout.includes('SUCCESS:')) {
                resolve(stdout.split('SUCCESS:')[1].trim());
            } else {
                reject(new Error(stdout || 'Unknown error from Python script'));
            }
        });
    });

    try {
        await runPython();

        // 6. Send Result
        const buffer = fs.readFileSync(outPath);
        const caption = `🎨 *Generated by Perchance*\n\n📝 *Prompt:* ${prompt}\n📐 *Shape:* ${ratioLabel}`;
        
        // Delete the loading message
        await sock.sendMessage(from, { delete: loadingMsg.key });

        await sock.sendMessage(from, { 
            image: buffer, 
            caption: caption 
        }, { quoted: msg });

        // Cleanup
        if (fs.existsSync(outPath)) fs.unlinkSync(outPath);

    } catch (error) {
        console.error('Imagine Command Error:', error);
        
        let errorMessage = '❌ Failed to generate image.';
        if (error.message.includes('Rate limit')) {
            errorMessage = '❌ Perchance rate limit exceeded. Try again later.';
        } else if (error.message.includes('AuthenticationError')) {
            errorMessage = '❌ Perchance authentication failed.';
        } else {
            errorMessage = `❌ Error: ${error.message.slice(0, 100)}...`;
        }

        await sock.sendMessage(from, { text: errorMessage, edit: loadingMsg.key });
        
        // Cleanup on error
        if (fs.existsSync(outPath)) fs.unlinkSync(outPath);
    }
};

